/** OpenAPI 3.0 spec for the Notification service. */
module.exports = {
  openapi: '3.0.3',
  info: {
    title: 'FEMS — Notification Service',
    version: '1.0.0',
    description: 'Read and manage user notifications generated by inspection/compliance events.',
  },
  servers: [
    { url: 'http://localhost:8080/api/notifications', description: 'Via API gateway' },
    { url: 'http://localhost:4005', description: 'Direct' },
  ],
  components: {
    securitySchemes: { bearerAuth: { type: 'http', scheme: 'bearer', bearerFormat: 'JWT' } },
  },
  security: [{ bearerAuth: [] }],
  paths: {
    '/notifications': {
      get: { tags: ['Notifications'], summary: 'List my notifications',
        parameters: [{ name: 'unread', in: 'query', schema: { type: 'boolean' } }],
        responses: { 200: { description: 'List' } } },
      post: { tags: ['Notifications'], summary: 'Create / broadcast (admin)',
        requestBody: { required: true, content: { 'application/json': { schema: {
          type: 'object', required: ['title', 'message'],
          properties: {
            userId: { type: 'string', format: 'uuid', description: 'Omit to broadcast to all' },
            type: { type: 'string' }, title: { type: 'string' }, message: { type: 'string' },
          },
        } } } },
        responses: { 201: { description: 'Created' } } },
    },
    '/notifications/{id}/read': {
      patch: { tags: ['Notifications'], summary: 'Mark one as read',
        parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }],
        responses: { 200: { description: 'OK' } } },
    },
    '/notifications/read-all': {
      post: { tags: ['Notifications'], summary: 'Mark all as read', responses: { 200: { description: 'OK' } } },
    },
    '/notifications/{id}': {
      delete: { tags: ['Notifications'], summary: 'Delete a notification',
        parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }],
        responses: { 204: { description: 'Deleted' } } },
    },
  },
};
